# localhost

GET http://localhost:8080/contacts
GET http://localhost:8080/contacts/6269934c28437d486bd8232c
GET http://localhost:8080/contacts/6269934c28437d486bd8232d
GET http://localhost:8080/contacts/6269934c28437d486bd8232e

# Production

GET https://personal-assignmenr-w02.herokuapp.com/contacts
GET https://personal-assignmenr-w02.herokuapp.com/contacts/6269934c28437d486bd8232c
GET https://personal-assignmenr-w02.herokuapp.com/contacts/6269934c28437d486bd8232d
GET https://personal-assignmenr-w02.herokuapp.com/contacts/6269934c28437d486bd8232e